_Note/
AotTest.sh
AotWin.sh
assets/
ClearWin.sh
CompileIfaceGenCli.sh
Compose.sh
CpAssets.sh
Doc/
ExternalRsrc/
GitSubMod.sh
Languages/
ls
Ngan.Dict.Core/
Ngan.Dict.Frontend/
Ngan.Dict.Backend/
Ngan.Dict.Server/
Ngan.Dict.sln
Ngan.Dict.Test/
Ngan.Dict-Debug.sqlite
proj/
PublishAndroid.sh
PublishWeb.sh
PublishWin.sh
README.md
README.typ
RemakeDb.sh
RunBrowser.sh
RunWin.sh
Spec.typ
TagAll.sh
TagEtPushRepo.sh
TagLibs.sh
Test.sh
Todo/
Tsinswreng.Avln.StrokeText/
Tsinswreng.AvlnTools/
Tsinswreng.CsCfg/
Tsinswreng.CsCore/
Tsinswreng.CsDictMapper/
Tsinswreng.CsErr/
Tsinswreng.CsFactoryMkr/
Tsinswreng.CsIfaceGen/
Tsinswreng.CsIfaceGen.Cli.exe
Tsinswreng.CsPage/
Tsinswreng.CsSql/
Tsinswreng.CsSrcGenTools/
Tsinswreng.CsTools/
Tsinswreng.CsTypeAlias/
Tsinswreng.JavaSqlHelper/
Tsinswreng.TypstTools/
UpdSln.sh
UserSpec.typ
VersionNote.typ
WebSrv.sh
WinWeb.sh
WordList.typ
